const quotes = [
    "\"Faster than 99% of other proxies!\" - ajh",
    "\"Thank you for using vault :)\" - ajh",
    "\"The best way to predict the future is to create it\" - Peter Drucker",
    "\"You miss 100% of the shots you don't take\" - Wayne Gretzky",
    "\"Lock in on school vroðŸ’”\" - ajh",
    "\"THIS SITE ACTUALLY HAS EDUCATIONAL ASPECTS\" - ajh",
    "TIP: Youre awesome!",
    "\"Thank you for using vault ❤️\" - ajh",
    "\"these games are ADA compliant, ♿/10\" - cts3696",
    "\"some of these quotes are from vault v6.0 so they might not make sense\" - ajh",
    "\"oh yeah btw roblox can never be added!\" - ajh",
    "\"click the links icon for more links (no duh) and bookmark the doc\" - ajh",
    "\"vault is goated\" - ajh",
    "\"to eat or not to eat\" - KilonÃ¸x",
    "\"random fact: vault has been in development since 2021\" - ajh",
    "\"BOOKMARK THIS SITE\" - ajh",
    "\"BOOKMARK THIS SITE AND THE LINK DOC\" - ajh",
    "\"100% educational fr\" - ajh",
    "\"thx jobi for bug fixes\" - ajh",
    "\"Be a good endis\" - ajh",
    "\"Kruger Kristi's basic ass burger makes me feel like Brian Griffin\" - cts3696",
    "\"I edge until my micro soft\" - cts3696",
    "\"ð“¦ð“¸ð“»ð“­ ð“Ÿð“»ð“®ð“­ð“²ð“¬ð“½ð“²ð“¸ð“·ð“¼\" - ajh",
    "\"https://www.youtube.com/watch?v=xpVfcZ0ZcFM\" - ajh",
    "\"Dickhead Glorious Taft III; Cause of death: epiglottitis\" - ajh",
    "\"Mcdonalda mcodoble recpie -1 meat -top bred -botom bed -che   ese -mcdurmick sose -plciejcle -cook it\" - cts3696",
    "\"And then hunt and then spit and then scrap yourself and then hunt for bears and then lick the honey then take off our pants and poop on top of nature\" - southernctrailfan",
    "\"D#DDY C#M ME INSIDE THE BATâ€™S P###S BEFORE IT TURNS INTO A TESTED LIGHT BULB AND EXPLODE\" - southernctrailfan",
    "\"ROCCO YOU BETTA STAWT LISTENIN IF NOT YA NOT COMIN OUT NO MOA\" - a random guy in nj",
    "\"9 + 10 = 21\" - ajh",
    "\"Hundreds of Yhousns\" - AbileneExplorer",
    "\"go do great things\" - ajh",
    "\"the A students are inventors\" - ajh",
    "TIP: Got a game suggestion? You can email aj@ajh.college!",
    "TIP: Use the Link Portal to have access to multiple links!",
    "TIP: Is a game you like not on here? You can search it up in the proxy!",
    "TIP: You can join our Discord for updates on new features/projects!",
    "TIP: Want to help Vault? You can share the Link Portal with your friends!",
    "TIP: If you want to take polls about Vault, join our Discord!",
    "TIP: Joining our Discord allows access to a large, chill community!",
    "\"id recommend not using the proxy to watch porn\" - ajh",
    "\"fun fact: 75% of 8th graders are not proficient in math\" - ajh",
    "\"Use the link portal\" - ajh",
    "\"pronouns: XÌŒlawg / VroðŸ’”\" - ajh",
    "\"congrats, you found a quote with no purpose other than the fact you found it\" - ajh",
    "\"30k users and counting\" - ajh",
    "\"youre cool ðŸ˜„ðŸ‘\" - ajh",
    "\"one of the fastest sites\" - ajh",
    "\"Press CTRL + D to bookmark!\" - ajh",
    "\"we love spacehey\" - ajh",
    "\"ajh.boats <- about me\" - ajh",
    "\"hello chat\" - ajh",
    "\"click that shiny purple button on the bottom right\" - ajh",
    "\"youre cool for using this site\" - ajh",
    "\"youre awesome for using this site\" - ajh",
    "\"youre epic for using this site\" - ajh",
    "\"skibidi toilet\" - ajh",
    "\"2036 heat death\" - ajh",
    "\"stupid endis\" - southernctrailfan's little brother",
    "\"my crush's initial is one of 26 letters\" - ajh",
    "\"sigma\" - ajh",
    "\"thats sigogglin\" - ajh but west virginian",
    "\"helloooooooooooooooooooooooooooooooooooooooooooooooooooooo\" - ajh",
    "\"this site can load apps that competitors cant!\" - ajh",
    "\"ctrl shift qq\" - ajh",
    "\"cuddling with natuski\" - pajammykid75",
    "\"Munching on ur earlobe\" - Bearcat",
    "\"teeming with life\" - molkify",
    "\"Dont think about it too much and if you cant, then get high\" - Grin",
    "\"swag\" - SkankFettucini",
    "\"HOORAY!! does this have like ... a proxy\" - tomochins",
    "\"TN is gay nvm\" - Bearcat",
    "\"Poop\" - Donut Dev",
    "\"BOOKMARK THE LINK DOC.\" - ajh",
    "\"BOOKMARK THE LINK PORTAL.\" - ajh",
    "\"USE THE LINK DOC.\" - ajh",
    "\"USE THE LINK PORTAL.\" - ajh",
    "\"guys whats 9+6 ... i need an answer\" - Technonyte",
    "\"was the hitler war in the 1800's?\" - WindowsSR",
    "\"loading apps others cantðŸ’ª\" - ajh",
    "\"bookmark the link doc\" - ajh",
    "\"bookmark the link doc pls\" - ajh",
    "\"hey you! bookmark the link doc pls\" - ajh",
    "\"if you want more links, bookmark the link doc pls\" - ajh",
    "\"if you want more links, bookmark the link doc\" - ajh",
    "\"v7 coming soon\" - ajh (Well that's a lie (this quote was from v6.0))",
    "\"anybody know sum fine shyts\" - ajh"
];
const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
document.querySelector('.quote-thing').textContent = randomQuote;